const { execFileSync, execSync } = require('child_process');
for (const file of ['main.js', 'preload.js', 'scripts/build.js', 'src/store.js', 'src/cloud.js', 'src/animeworld.js', 'src/animeunity.js', 'src/source-check.js', 'src/source-discovery.js', 'src/series-addition.js', 'test/source-discovery.js', 'src/player.js', 'src/mpv-manager.js', 'src/franchise.js', 'src/metadata.js', 'renderer/app.js', 'renderer/i18n.js']) execFileSync(process.execPath, ['--check', file], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/animeworld.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/animeunity.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/source-check.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/player-sources.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/mpv-manager.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['test/run.js'], { stdio: 'inherit' });
for(const file of ['src/episode-ratings.js','test/audit-regressions.js','test/renderer-electron.js','test/renderer-runner.js']) execFileSync(process.execPath,['--check',file],{stdio:'inherit'});
if(process.platform !== 'linux' || process.env.DISPLAY) execFileSync(process.execPath, ['test/renderer-runner.js'], { stdio: 'inherit' });
else console.log('Electron DOM/input tests skipped: no Linux display is available. Run with xvfb or a desktop session.');
execSync('git diff --check', { stdio: 'inherit' });
console.log('All checks passed.');
